### ISSUE TITLE
Invited user stuck at /activate after registering

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1147]
"I was added as an additional user to an existing site yesterday and managed to register. However, I am stuck on the /activate page and sentry has been throwing an error. Tried on multiple devices and at different times"

**Comment by edmundojr** [comment]
Same happening here, users can’t seem to activate their accounts. It happens for Admins and Viewers alike.

**Comment by MarkusAtEnreach** [comment]
Same happening at our sites. Any known workaround?

**Comment by metmarkosaric** [comment]
sorry for the inconvenience! we're looking at this and will update as soon as there's a fix. in the meanwhile, if you need to share the stats right now, [our shared links](https://plausible.io/docs/shared-links) are a good alternative

**Comment by MarkusAtEnreach** [comment]
For viewers using shared links is a workaround, but not for admins. We have several domains and I need to distribute work.

**Comment by metmarkosaric** [comment]
this is a brand new functionality we just released thursday last week. seems like for some specific cases, there's a bug and we're looking into it. it only affects a few invited users so we're trying to figure out what's going on. when there's an update, we will fix it and share here. at the moment, if your invited user is stuck at /activate and needs admin access there's no workaround until we fix it

**Comment by mat-hil** [comment]
I had the initial case from the issue: The issue was resolved for me earlier today - I did not do anything different from before, the activate page just started working again.

**Comment by ukutaht** [comment]
Just pushed a fix for this. Seems to affect people who were invited to more than 1 site at a time. Sorry about this and it would be helpful to hear back if it was fixed :)

**Comment by MarkusAtEnreach** [comment]
It is partially fixed. User can login now, but if they login, the see a trial:
![image](https://user-images.githubusercontent.com/86395489/123617240-55283080-d807-11eb-9c60-8c1fc63ee064.png)

**Comment by metmarkosaric** [comment]
Thanks for the update @MarkusAtEnreach! This is expected. After the 30 days of trial the message will go away and they will continue having access to any sites you have given them access to even without having their own subscription. If the invited user adds a brand new site and becomes an owner of that site than the trial comes into effect and they'll need to subscribe to a plan to continue viewing the stats of the site they own after the 30 days of trial.

**Comment by MarkusAtEnreach** [comment]
Thanks!
